/**:
  ros__parameters:
    min_longitudinal_offset: 0.2
    max_longitudinal_offset: 1.3
    min_lateral_offset: -0.52
    max_lateral_offset: 0.52
    min_height_offset: 0.2
    max_height_offset: 1.3
