/**:
  ros__parameters:
    wheel_radius: 0.15 # The radius of the wheel, primarily used for dead reckoning.
    wheel_width: 0.1 # The lateral width of a wheel tire, primarily used for dead reckoning.
    wheel_base: 1.04 # betweente front wheel cenr and rear wheel center
    wheel_tread: 0.565 # between left wheel center and right wheel center
    front_overhang: 0.15 # between front wheel center and vehicle front
    rear_overhang: 0.15 # between rear wheel center and vehicle rear
    left_overhang: 0.128 # between left wheel center and vehicle left
    right_overhang: 0.128 # between right wheel center and vehicle right
    vehicle_height: 1.1
    max_steer_angle: 0.2268 # [rad]